version: '3.8'

services:
	api:
		build: ./api
		container_name: api
		ports:
			- "8000:8000"
		depends_on:
			- mongodb
	mongodb:
		image: mongo
		container_name: mongodb
		ports:
			- "27017:27017"
		volumes:
			- /var/lib/mongodb:/data/db
	frontend:
		build: ./front
		container_name: frontend
		ports:
			- "3000:80" # Mapea puerto 3000 al puerto 80 del contenedor (Apache)
		depends_on:
			- api